#### Python debugger

Rewrite Matloff's example in Python.  Try to keep a similar organization.

[**insertion-sort.0.py**](../code/insertion-sort.0.py)

One way to start the debugger.  From the ``debug`` folder:

```
python -m pdb code/insertion-sort.0.py 3 2 1
```

So let's do that, set a breakpoint on ``process_data`` and ``run``.

```
> python -m pdb code/insertion-sort.0.py 3 2 1
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(1)<module>()
-> import sys
(Pdb) b process_data
Breakpoint 1 at /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py:30
(Pdb) r
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(31)process_data()
-> for v in x:
(Pdb) p x
[3, 2, 1]
(Pdb) p y
[]
(Pdb)
```

We print the variables ``x`` and ``y`` and they look correct.

Now actually, before doing any debugging, if we try the program, there is a big hint to the first bug:

```
> python -m pdb code/insertion-sort.0.py 2 1
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(1)<module>()
-> import sys
(Pdb) b scoot_over
Breakpoint 1 at /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py:12
(Pdb) r
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(14)scoot_over()
-> y.append(0)
(Pdb) s
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(15)scoot_over()
> -> k = len(y) - 1
```

Print some variables:

```
(Pdb) p y
[2, 0]
(Pdb) p k
*** NameError: NameError("name 'k' is not defined",)
(Pdb) s
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(16)scoot_over()
-> while k > jj:
(Pdb) p k
1
(Pdb) s
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(17)scoot_over()
-> y[k] = y[k-1]
(Pdb) s
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(18)scoot_over()
-> k += 1
(Pdb) p k
1
(Pdb) p y
[2, 2]
(Pdb) s
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(16)scoot_over()
-> while k > jj:
(Pdb) s
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(17)scoot_over()
-> y[k] = y[k-1]
(Pdb) p k
2
(Pdb) s
IndexError: 'list assignment index out of range'
> /Users/telliott_admin/Desktop/debug/code/insertion-sort.0.py(17)scoot_over()
-> y[k] = y[k-1]
(Pdb) 
```

Actually, we don't need the debugger for this.

```
> python debug/code/insertion-sort.0.py
gimme some numbers
> python debug/code/insertion-sort.0.py 2 1
Traceback (most recent call last):
  File "debug/code/insertion-sort.py", line 43, in <module>
    process_data(x)
  File "debug/code/insertion-sort.0.py", line 35, in process_data
    insert(v)
  File "debug/code/insertion-sort.0.py", line 29, in insert
    scoot_over(j)
  File "debug/code/insertion-sort.0.py", line 17, in scoot_over
    y[k] = y[k-1]
IndexError: list assignment index out of range
>
```

The fact that ``k`` is out of range immediately suggests it's being incremented rather than decremented.

So edit the code for ``scoot_over``:

```
        k -= 1
```

There are still problems:

```
> python code/insertion-sort.1.py 3 2 1
1
1
2
3
> python code/insertion-sort.1.py 1 2 3
^Z
[7]+  Stopped                 python code/insertion-sort.py 1 2 3
>
```

Rather than work through the rest of this, just make the other fixes:

[**insertion-sort.py**](../code/insertion-sort.py)
